### PR TITLE
Measurement of scrollbar width made async

### PR DESCRIPTION
**Pull request by jalooc**
Hi there, great repo! I found however one glitch: although the scrollbar seemed to work perfectly fine on the examples web page, it didn't work in my projects at all. I spent half a day finding out what I was doing wrong. Eventually I discovered, that maybe it's not my fault after all and it seemed to be bit of luck that for most people it works. Namely, the measurement of scrollbar was being done by injecting a temporary div into `body`, applying a specific class and measuring the widths of the aftermath. And it was all done synchronously. In my case however, the browser didn't catch up* with all the actions and the measurements were done before the styles application took effect. Thus I was ending up with the apparently default for Chrome 405px offsetWidth and clientWidth.

Putting the measurement action in `setTimeout` to invoke at the end of the event loop solved the problem. This aroused some synchronicity problems. One part was simply solved with callback, but then there was the need of handling potential call by user of methods like `create()` before the measurement was finished. I saw that the module was written in es5, therefore I didn't want to introduce any async functions or add dependencies etc. I decided to make a simple queue of actions to be done after measurement.

Cheers,
Peter.

* I deduced it didn't catch up by simply logging the measurements in the `getScrollbarWidth()` function and then after wrapping it in `setTimeout()`. Of course first reading was wrong and second correct. NOTE: this only happened on initial render. I'm not sure why, but maybe due to a bloat of work to be done by browser engine and slowing down with rendering styles.

### CODE REVIEW

**Comment by noeldelgado** [comment]
Thank you @jalooc!, any chance you can provide a test case reproducing the issue? (http://jsfiddle.net, http://jsbin.com/, http://codepen.io/, etc). I am curious about how this can happen.

**Comment by jalooc** [comment]
As I wrote, I deduced that it must be caused by the bloat of work for browser at initial page load. I'm not sure how this could be simulated on any repl. Anyway, if you give the situation a little more consideration, the diagnosis is totally reasonable - the measured div's size was the default 405px, even though when I checked in dev tools, it was correctly set to 100px. It's clearly the matter of styles not being rendered fast enough. Now I'm not sure if a simple `setTimeout(f())` is enough. It helped in my case, but I don't know if styles rendering for any browser takes exactly one event loop cycle or more.

**Comment by noeldelgado** [comment]
Hi @jalooc, I think I was able to replicate it. Your diagnosis led me to the follow hypothesis.

If styles are not being applied when running the getScrollbar fn, then applying the styles when calling the fn will ensure the test element is updated when asking for its dimensions.

So by modifying the `getScrollbarWidth` function as follow solved the problem for me:

```js
function getScrollbarWidth() {
    var el = document.createElement('div');
    el.style.position = 'absolute';
    el.style.top = '-9999px';
    el.style.width = '100px';
    el.style.height = '100px';
    el.style.overflow = 'scroll';
    el.style.msOverflowStyle = 'scrollbar';
    document.body.appendChild(el);
    return (el.offsetWidth - el.clientWidth);
}
```

Can you try it and see if that works for you too? Months ago I made the silly decision of moving these declarations to the stylesheet, which at that point seemed a bad idea but I did it anyway :/ I think this is one of its consequences.

Thank you.

**Comment by jalooc** [comment]
Bingo ;) A lot better solution then mine.

As to styles managing - when I'm composing a component whose correct behavior depend on styles, I tend to keep the _must-have_ styles inline, whilst allowing the user to style anything else by class names for easy customization. So far this methodology has been very efficient for me.

Cheers.

**Comment by noeldelgado** [comment]
Cool, do you want to update this PR or should I close it?

The changes are basically:
- index.js - update the `getScrollbarWidth` function as above
- index.js - remove the `scrollbarWidthTest` key from the `CLASSNAMES` dictionary
- gemini-scrollbar.css - remove the `.gm-test` css rule

Thanks again for your help, I really appreciate it. :+1:

**Comment by noeldelgado** [comment]
Done [@v1.3.1](https://github.com/noeldelgado/gemini-scrollbar/releases/tag/v1.3.1).

**Pull request closed without merging**
